spring:
  application:
    name:service-consumer

server:
  port: 8888

service-provider:
  ribbon:
    eureka:
      enabled: false
    listOfServers: localhost:8090,localhost:9092,localhost:9999
    ServerListRefreshInterval: 15000
